# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Final Hypothesis testing
#'
#' @param y observed binary outcome data
#' @param theta0 reference theta for H0
#'
#' @export
pbCfYtest <- function(y, theta0) {
    .Call(`_pbiom_pbCfYtest`, y, theta0)
}

#' Predict for a single set of value for rep times
#'
#' @param rep number of replications
#' 
#'
#' @export
pbCfPredSingle <- function(vq, vp, n2, theta0, alpha, rep, rst) {
    invisible(.Call(`_pbiom_pbCfPredSingle`, vq, vp, n2, theta0, alpha, rep, rst))
}

#' Predict for posterior samples from the interim analysis
#'
#' 
#' 
#'
#' @export
pbCfPred <- function(vq, vp, n2, theta0, alpha, repeach) {
    .Call(`_pbiom_pbCfPred`, vq, vp, n2, theta0, alpha, repeach)
}

#' Get utilities
#'
#'
#' @export
pbCfUti <- function(prst, utif, theta0, estt, B1, C1, C2, C3) {
    .Call(`_pbiom_pbCfUti`, prst, utif, theta0, estt, B1, C1, C2, C3)
}

#' Test function
#'
#' @param u input value
#' @return u squared 
#' @export
ptemp <- function(u) {
    .Call(`_pbiom_ptemp`, u)
}

